### ISSUE TITLE
Error: Chrome user data dir not found at

### ISSUE THREAD

**Issue by CDP1PROM1N** [morko/haxroomie#121]
Hi guys. Out of nowhere I got this error when trying to deploy to AWS (following your instructions). Any idea what it is due to?
Thanks for your time.

[2022-02-05T03:58:38.127Z] [error] Error: Chrome user data dir not found at '/home/ubuntu/.haxroomie/user-data-dir'
    at ChromeLauncher.launch (/home/ubuntu/.nvm/versions/node/v12.16.3/lib/node_modules/haxroomie-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:87:23)
    at PuppeteerNode.launch (/home/ubuntu/.nvm/versions/node/v12.16.3/lib/node_modules/haxroomie-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:125:31)
    at Haxroomie.launchBrowser (/home/ubuntu/.nvm/versions/node/v12.16.3/lib/node_modules/haxroomie-cli/node_modules/haxroomie-core/src/Haxroomie.js:132:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createHaxroomie (/home/ubuntu/.nvm/versions/node/v12.16.3/lib/node_modules/haxroomie-cli/node_modules/haxroomie-core/index.js:19:3)
    at async HRConsoleApp.start (/home/ubuntu/.nvm/versions/node/v12.16.3/lib/node_modules/haxroomie-cli/src/HRConsoleApp.js:49:22)
    at async bootstrap (/home/ubuntu/.nvm/versions/node/v12.16.3/lib/node_modules/haxroomie-cli/index.js:49:5)

**Comment by jstnh08** [comment]
I have the same issue- ubuntu 18.04

**Comment by jstnh08** [comment]
Just found a solution, manually add the `user-data-dir`.

**Comment by morko** [comment]
Fixed in de9ec7f221bb028b02a897fea6e04528ec5a8e9a. Please note that Node.js version should be 16 in new version.
