### ISSUE TITLE
 [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections

### ISSUE THREAD

**Issue by damian18zb** [morko/haxroomie#124]
haxroomie-cli 2.6.4
node v16.18.0

When running a host for about a week this error appars and it is not possible to join the room. Restarting haxroomie fixes this issue.

```
[2023-12-29T14:24:21.301Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
[2023-12-29T14:26:33.456Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
[2023-12-29T14:28:04.258Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
[2023-12-29T14:28:16.959Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
[2023-12-29T14:28:18.419Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
[2023-12-29T14:28:46.107Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
[2023-12-29T14:32:03.823Z] [error] DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Ja (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:64:442)
    at Ka.bh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:95:287)
    at Ka.ah (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:468)
    at Ka.dh (https://www.haxball.com/8TJol3VA/__cache_static__/g/headless-min.js:94:150)
```

**Comment by morko** [comment]
Hey thanks for your bug report. I have not been developing haxroomie for a while and not running any rooms. Please join the discord and ask if anyone else is experiencing these problems https://discord.gg/TeJAEWu.

These errors seem to happen when WebRTC are made and not cleaned up. Haxroomie itself is not making any WebRTC connections but haxball is. It would be useful to know how many rooms are you running, are they public or private, are you running the default haxball source and which plugins are you running in those rooms.

**Comment by damian18zb** [comment]
Thanks for discord invitation, I am already there.
I am running one public room without plugins.
I do not really get what you mean with "default haxball source"?

**Comment by damian18zb** [comment]
If you mean source code, well I am running 5,5k+ lines own script.
